# # #

name: navegante-cms-development

volumes:
  cmsdbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  websitedb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 39101:27017
    volumes:
      - cmsdbdata:/data/db
    env_file:
      - ./secrets/.env